import { z } from 'zod';
import { ThemeConfigSchema, type ThemeConfig } from './menus.js';

export const ThemePresetSchema = z.object({
  id: z.string(),
  name: z.string(),
  preview: z.string().url().optional(),
  config: ThemeConfigSchema,
});

export type ThemePreset = z.infer<typeof ThemePresetSchema>;

// Default theme presets
export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'classic',
    name: 'Classic',
    config: {
      primaryColor: '#1f2937',
      backgroundColor: '#ffffff',
      textColor: '#1f2937',
      fontFamily: 'Georgia',
      borderRadius: 0,
      layout: 'list',
      showImages: true,
      showDescriptions: true,
      showPrices: true,
      showTags: true,
    },
  },
  {
    id: 'modern',
    name: 'Modern',
    config: {
      primaryColor: '#3b82f6',
      backgroundColor: '#ffffff',
      textColor: '#1f2937',
      fontFamily: 'Inter',
      borderRadius: 8,
      layout: 'list',
      showImages: true,
      showDescriptions: true,
      showPrices: true,
      showTags: true,
    },
  },
  {
    id: 'elegant',
    name: 'Elegant',
    config: {
      primaryColor: '#7c3aed',
      backgroundColor: '#faf5ff',
      textColor: '#1e1b4b',
      fontFamily: 'Playfair Display',
      borderRadius: 12,
      layout: 'list',
      showImages: true,
      showDescriptions: true,
      showPrices: true,
      showTags: true,
    },
  },
  {
    id: 'dark',
    name: 'Dark',
    config: {
      primaryColor: '#f59e0b',
      backgroundColor: '#111827',
      textColor: '#f9fafb',
      fontFamily: 'Inter',
      borderRadius: 8,
      layout: 'list',
      showImages: true,
      showDescriptions: true,
      showPrices: true,
      showTags: true,
    },
  },
  {
    id: 'rustic',
    name: 'Rustic',
    config: {
      primaryColor: '#92400e',
      backgroundColor: '#fef3c7',
      textColor: '#451a03',
      fontFamily: 'Merriweather',
      borderRadius: 4,
      layout: 'list',
      showImages: true,
      showDescriptions: true,
      showPrices: true,
      showTags: true,
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    config: {
      primaryColor: '#000000',
      backgroundColor: '#ffffff',
      textColor: '#000000',
      fontFamily: 'Inter',
      borderRadius: 0,
      layout: 'compact',
      showImages: false,
      showDescriptions: false,
      showPrices: true,
      showTags: false,
    },
  },
  {
    id: 'bold',
    name: 'Bold',
    config: {
      primaryColor: '#dc2626',
      backgroundColor: '#fef2f2',
      textColor: '#1f2937',
      fontFamily: 'Poppins',
      borderRadius: 16,
      layout: 'grid',
      showImages: true,
      showDescriptions: true,
      showPrices: true,
      showTags: true,
    },
  },
  {
    id: 'coastal',
    name: 'Coastal',
    config: {
      primaryColor: '#0891b2',
      backgroundColor: '#ecfeff',
      textColor: '#164e63',
      fontFamily: 'Open Sans',
      borderRadius: 12,
      layout: 'list',
      showImages: true,
      showDescriptions: true,
      showPrices: true,
      showTags: true,
    },
  },
  {
    id: 'warm',
    name: 'Warm',
    config: {
      primaryColor: '#ea580c',
      backgroundColor: '#fff7ed',
      textColor: '#431407',
      fontFamily: 'Lato',
      borderRadius: 8,
      layout: 'list',
      showImages: true,
      showDescriptions: true,
      showPrices: true,
      showTags: true,
    },
  },
  {
    id: 'night',
    name: 'Night',
    config: {
      primaryColor: '#a78bfa',
      backgroundColor: '#0f172a',
      textColor: '#e2e8f0',
      fontFamily: 'Inter',
      borderRadius: 8,
      layout: 'list',
      showImages: true,
      showDescriptions: true,
      showPrices: true,
      showTags: true,
    },
  },
];

export const FONT_OPTIONS = [
  'Inter',
  'Georgia',
  'Playfair Display',
  'Merriweather',
  'Open Sans',
  'Roboto',
  'Lato',
  'Poppins',
];
