/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as MVenueSlugRouteImport } from './routes/m/$venueSlug'
import { Route as DashboardAnalyticsRouteImport } from './routes/_dashboard/analytics'
import { Route as DashboardVenuesIndexRouteImport } from './routes/_dashboard/venues/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard/settings/index'
import { Route as DashboardQrCodesIndexRouteImport } from './routes/_dashboard/qr-codes/index'
import { Route as DashboardMenusIndexRouteImport } from './routes/_dashboard/menus/index'
import { Route as DashboardVenuesNewRouteImport } from './routes/_dashboard/venues/new'
import { Route as DashboardVenuesVenueIdRouteImport } from './routes/_dashboard/venues/$venueId'
import { Route as DashboardMenusNewRouteImport } from './routes/_dashboard/menus/new'
import { Route as DashboardMenusMenuIdIndexRouteImport } from './routes/_dashboard/menus/$menuId/index'
import { Route as DashboardMenusMenuIdEditorRouteImport } from './routes/_dashboard/menus/$menuId/editor'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const MVenueSlugRoute = MVenueSlugRouteImport.update({
  id: '/m/$venueSlug',
  path: '/m/$venueSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVenuesIndexRoute = DashboardVenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQrCodesIndexRoute = DashboardQrCodesIndexRouteImport.update({
  id: '/qr-codes/',
  path: '/qr-codes/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenusIndexRoute = DashboardMenusIndexRouteImport.update({
  id: '/menus/',
  path: '/menus/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVenuesNewRoute = DashboardVenuesNewRouteImport.update({
  id: '/venues/new',
  path: '/venues/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVenuesVenueIdRoute = DashboardVenuesVenueIdRouteImport.update({
  id: '/venues/$venueId',
  path: '/venues/$venueId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenusNewRoute = DashboardMenusNewRouteImport.update({
  id: '/menus/new',
  path: '/menus/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenusMenuIdIndexRoute =
  DashboardMenusMenuIdIndexRouteImport.update({
    id: '/menus/$menuId/',
    path: '/menus/$menuId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMenusMenuIdEditorRoute =
  DashboardMenusMenuIdEditorRouteImport.update({
    id: '/menus/$menuId/editor',
    path: '/menus/$menuId/editor',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/analytics': typeof DashboardAnalyticsRoute
  '/m/$venueSlug': typeof MVenueSlugRoute
  '/': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/menus/new': typeof DashboardMenusNewRoute
  '/venues/$venueId': typeof DashboardVenuesVenueIdRoute
  '/venues/new': typeof DashboardVenuesNewRoute
  '/menus': typeof DashboardMenusIndexRoute
  '/qr-codes': typeof DashboardQrCodesIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/venues': typeof DashboardVenuesIndexRoute
  '/menus/$menuId/editor': typeof DashboardMenusMenuIdEditorRoute
  '/menus/$menuId': typeof DashboardMenusMenuIdIndexRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof DashboardAnalyticsRoute
  '/m/$venueSlug': typeof MVenueSlugRoute
  '/': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/menus/new': typeof DashboardMenusNewRoute
  '/venues/$venueId': typeof DashboardVenuesVenueIdRoute
  '/venues/new': typeof DashboardVenuesNewRoute
  '/menus': typeof DashboardMenusIndexRoute
  '/qr-codes': typeof DashboardQrCodesIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/venues': typeof DashboardVenuesIndexRoute
  '/menus/$menuId/editor': typeof DashboardMenusMenuIdEditorRoute
  '/menus/$menuId': typeof DashboardMenusMenuIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/analytics': typeof DashboardAnalyticsRoute
  '/m/$venueSlug': typeof MVenueSlugRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_dashboard/menus/new': typeof DashboardMenusNewRoute
  '/_dashboard/venues/$venueId': typeof DashboardVenuesVenueIdRoute
  '/_dashboard/venues/new': typeof DashboardVenuesNewRoute
  '/_dashboard/menus/': typeof DashboardMenusIndexRoute
  '/_dashboard/qr-codes/': typeof DashboardQrCodesIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/_dashboard/venues/': typeof DashboardVenuesIndexRoute
  '/_dashboard/menus/$menuId/editor': typeof DashboardMenusMenuIdEditorRoute
  '/_dashboard/menus/$menuId/': typeof DashboardMenusMenuIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/analytics'
    | '/m/$venueSlug'
    | '/'
    | '/onboarding'
    | '/menus/new'
    | '/venues/$venueId'
    | '/venues/new'
    | '/menus'
    | '/qr-codes'
    | '/settings'
    | '/venues'
    | '/menus/$menuId/editor'
    | '/menus/$menuId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/m/$venueSlug'
    | '/'
    | '/onboarding'
    | '/menus/new'
    | '/venues/$venueId'
    | '/venues/new'
    | '/menus'
    | '/qr-codes'
    | '/settings'
    | '/venues'
    | '/menus/$menuId/editor'
    | '/menus/$menuId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/analytics'
    | '/m/$venueSlug'
    | '/_dashboard/'
    | '/onboarding/'
    | '/_dashboard/menus/new'
    | '/_dashboard/venues/$venueId'
    | '/_dashboard/venues/new'
    | '/_dashboard/menus/'
    | '/_dashboard/qr-codes/'
    | '/_dashboard/settings/'
    | '/_dashboard/venues/'
    | '/_dashboard/menus/$menuId/editor'
    | '/_dashboard/menus/$menuId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  MVenueSlugRoute: typeof MVenueSlugRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/m/$venueSlug': {
      id: '/m/$venueSlug'
      path: '/m/$venueSlug'
      fullPath: '/m/$venueSlug'
      preLoaderRoute: typeof MVenueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/analytics': {
      id: '/_dashboard/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/venues/': {
      id: '/_dashboard/venues/'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof DashboardVenuesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/qr-codes/': {
      id: '/_dashboard/qr-codes/'
      path: '/qr-codes'
      fullPath: '/qr-codes'
      preLoaderRoute: typeof DashboardQrCodesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/menus/': {
      id: '/_dashboard/menus/'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof DashboardMenusIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/venues/new': {
      id: '/_dashboard/venues/new'
      path: '/venues/new'
      fullPath: '/venues/new'
      preLoaderRoute: typeof DashboardVenuesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/venues/$venueId': {
      id: '/_dashboard/venues/$venueId'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId'
      preLoaderRoute: typeof DashboardVenuesVenueIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/menus/new': {
      id: '/_dashboard/menus/new'
      path: '/menus/new'
      fullPath: '/menus/new'
      preLoaderRoute: typeof DashboardMenusNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/menus/$menuId/': {
      id: '/_dashboard/menus/$menuId/'
      path: '/menus/$menuId'
      fullPath: '/menus/$menuId'
      preLoaderRoute: typeof DashboardMenusMenuIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/menus/$menuId/editor': {
      id: '/_dashboard/menus/$menuId/editor'
      path: '/menus/$menuId/editor'
      fullPath: '/menus/$menuId/editor'
      preLoaderRoute: typeof DashboardMenusMenuIdEditorRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardMenusNewRoute: typeof DashboardMenusNewRoute
  DashboardVenuesVenueIdRoute: typeof DashboardVenuesVenueIdRoute
  DashboardVenuesNewRoute: typeof DashboardVenuesNewRoute
  DashboardMenusIndexRoute: typeof DashboardMenusIndexRoute
  DashboardQrCodesIndexRoute: typeof DashboardQrCodesIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardVenuesIndexRoute: typeof DashboardVenuesIndexRoute
  DashboardMenusMenuIdEditorRoute: typeof DashboardMenusMenuIdEditorRoute
  DashboardMenusMenuIdIndexRoute: typeof DashboardMenusMenuIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardMenusNewRoute: DashboardMenusNewRoute,
  DashboardVenuesVenueIdRoute: DashboardVenuesVenueIdRoute,
  DashboardVenuesNewRoute: DashboardVenuesNewRoute,
  DashboardMenusIndexRoute: DashboardMenusIndexRoute,
  DashboardQrCodesIndexRoute: DashboardQrCodesIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardVenuesIndexRoute: DashboardVenuesIndexRoute,
  DashboardMenusMenuIdEditorRoute: DashboardMenusMenuIdEditorRoute,
  DashboardMenusMenuIdIndexRoute: DashboardMenusMenuIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  MVenueSlugRoute: MVenueSlugRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
