// This file is auto-generated by TanStack Router.
// Do not edit this file manually.

import { Route as rootRoute } from './routes/__root'
import { Route as VenueSlugRoute } from './routes/$venueSlug'

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof rootRoute
      parentRoute: typeof rootRoute
    }
    '/$venueSlug': {
      preLoaderRoute: typeof VenueSlugRoute
      parentRoute: typeof rootRoute
    }
  }
}

export const routeTree = rootRoute.addChildren([VenueSlugRoute])